<section id="sme" class="body row">

    <section id="yuspify-pricing" class="row">
        <div id="title-box">
            <h1>Pay as we help you grow</h1>
            <h2>Simple, personalized pricing based on the revenue generated through Yuspify.</h2>
        </div>

        <div id="pricing-box" class="fluid-container">

            <div id="pricing-inner">

                <div class="wrapper">
                    <div id="display-pricing">
                        <h2 id="the-price">
                            $<span></span>
                        </h2>
                        <h3>Monthly fee</h3>
                    </div>

                    <div id="pricing-form" class="hidden yfy-form-wrapper blue">
                        <h2>Contact Us!</h2>
                        <?php echo do_shortcode('[contact-form-7 id="4250" title="pricing page"]'); ?>
                    </div>
                </div>

            </div>

            <div id="pricing-slider" class="dragdealer">
                <div class="grabber handle">
                </div>
                <div id="monthly-revenue">
                    <h2><span>$</span><span class="revenue">29</span></h2>
                    <h3>Your monthly revenue</h3>
                </div>
            </div>

            <div id="pricing-parameters">
                <div>
                    <h2>$<span class="yusp-generated-revenue"></span><br>
                        generated by Yuspify
                    </h2>
                </div>
                <div>
                    <h2><span class="revenue-share">0</span>%<br>
                        revenue share by Yuspify
                    </h2>
                </div>
            </div>
        </div>
        <img class="pricing-mask" src="<?php echo get_stylesheet_directory_uri(); ?>/img/svg/pricing-mask.svg" alt="">
    </section>

    <section id="roi-positive" class="row">
        <div class="yfy-container">
            <h2 class="section-title purple">ROI positive solution</h2>
            <p class="paragraph">All features included, unlimited usage</p>
            <img class="roi" src="<?php echo get_stylesheet_directory_uri(); ?>/img/svg/roi-positive-solution.svg" alt="">
        </div>
    </section>

    <section id="pricing-features">

    </section>

</section>
